### ISSUE TITLE
Add screenshots to Plugin 

### ISSUE THREAD

**Issue by Poliuk** [worona/worona-wp-plugin#18]
Plugin Readme generator: https://generatewp.com/plugin-readme/
WordPress Readme.txt validator: https://wordpress.org/plugins/about/validator/
Plugin Readme example: https://wordpress.org/plugins/about/readme.txt

**Comment by rmartinezduque** [comment]
@Poliuk the sections `Description`, `Installation`, `FAQ`, `Changelog` & `Useful links` are done.

These other ones are **still to be completed**:

* **Plugin** (plugin name, contributors, tags, donate link, license, license URI).
* **Versions** (requires at least, tested up to, stable tag).
* **Screenshots** - I already made the dashboard and plugin screenshots - the app screenshots are missing and they all have to be uploaded.
* **Upgrade notice**.

**Comment by Poliuk** [comment]
Done: 

- **Plugin**
- **Versions**
- **Upgrade notice**
