### ISSUE TITLE
Create /discover endpoint

### ISSUE THREAD

**Issue by Poliuk** [worona/worona-wp-plugin#19]
Create `/discover?first_folder=XXX&last_folder=XXXX` endpoint. It has to use `is_category()`, `is_single()`,`is_author()`... 

And return `{id = XXX, type= XXX} `

> old comment: https://github.com/B3ST/B3-REST-API/blob/master/helpers/B3_RoutesHelper.php

**Comment by Poliuk** [comment]
@luisherranz we opened this issue 2 months ago haha

**Comment by Poliuk** [comment]
The endpoint is now working.

#### Endpoint 
`/discover`

#### Params
`first_folder`
`last_folder`

#### Supports
- Post
- Page
- Author
- Category
- Tag
- Custom Post type
- Custom Taxonomy

**Comment by luisherranz** [comment]
💪
