### ISSUE TITLE
Worona siteid endpoin returns rest_invalid_handler

### ISSUE THREAD

**Issue by luisherranz** [worona/worona-wp-plugin#23]
In this site: `http://www.bookproacts.com/testsite/?rest_route=/worona/v1/siteid`

It's a WordPress 4.7.2 running Twenty Sixteen theme, Worona 1.0 and WP REST API Version 2.0-beta15. Select WP Crontrol (Not Activated) Version 1.3.1 and WP-Cron Control (Not Activated) Version 0.7.1

- [x] After fix, send an email to the owner.

**Comment by Poliuk** [comment]
Tried to reproduce the issue in my local enviroment (WP 4.7.2 + Worona 1.0 + WP REST API Version 2.0-beta15), and I can't reproduce the error. 

I'm going to take a look to related issues with `rest_invalid_handler `

**Comment by Poliuk** [comment]
```
{
   code: "rest_invalid_handler",
   message: "The handler for the route is invalid",
   data: {
      status: 500
   }
}
```

There are two other users with the same problem:

- [gen7outdoors.com](http://gen7outdoors.com)
- [segredosdoconsumidor.hospedagemdesites.ws](http://segredosdoconsumidor.hospedagemdesites.ws) 

The second user also reports this error:

```
Parse error: syntax error, unexpected T_FUNCTION in /home/storage/1/b2/9b/segredosdoconsumidor/public_html/wp-content/plugins/worona/worona.php on line 60
```

**Comment by Poliuk** [comment]
another user with the same issue
- [malcocinado.org](http://malcocinado.org)

```
T_FUNCTION in /var/www/vhosts/malcocinado.org/httpdocs/wp-content/plugins/worona/worona.php on line 60
```

**Comment by Poliuk** [comment]
another one
- http://twodutchguys.nl/

**Comment by Poliuk** [comment]
It's an issue related with PHP version. It only works from PHP 5.4 and above.

**Comment by luisherranz** [comment]
Great!

**Comment by Poliuk** [comment]
The problem occurs in sites with PHP version lower than 5.4. In the examples above the PHP version  is 5.3 (which was released 6 years ago). Its not our plugin which is crashing but the WP REST API. 

So we only can encourage them to upgrade their PHP versions.

**Comment by Poliuk** [comment]
I've just updated the docs: https://docs.worona.org/plugin/troubleshooting.html

**Comment by Poliuk** [comment]
I've contacted the following users that have been mentioned in this issue:

- [x] http://segredosdoconsumidor.hospedagemdesites.ws
- [x] http://twodutchguys.nl/
- [x] http://malcocinado.org
- [x] gen7outdoors.com
- [x] http://www.bookproacts.com/

**Comment by Poliuk** [comment]
@luisherranz I let you close the issue. From my point of view we can't do anything more... But maybe you have an idea.

**Comment by luisherranz** [comment]
Ok. It's a WP-API problem so there's not much we can do.
