### ISSUE TITLE
html audio  tag not working

### ISSUE THREAD

**Issue by auliving** [worona/worona-wp-plugin#35]
html audio  tag not working in the pages.

the audio can's display in the iphone app.

but it working well at mobile browser.

**Comment by auliving** [comment]
at wordpress post editor, the source code like 
[embed] a mp3 file's url[/embed]

**Comment by auliving** [comment]
in html code, it is 
<audio ...
please fix it ASAP.
I bought pro theme. please fix it ASAP.

**Comment by Poliuk** [comment]
Hello @auliving, can you write to support@worona.org so we can link the issue to your Starter PRO order?

**Comment by Poliuk** [comment]
Moved here: https://github.com/worona/starter-pro-app-theme-worona/issues/40
