### ISSUE TITLE
Expose Yoast fields in Rest API

### ISSUE THREAD

**Issue by orballo** [worona/worona-wp-plugin#42]
- Test https://github.com/ChazUK/wp-api-yoast-meta
- If it works, fork it and add the missing fields

**Comment by luisherranz** [comment]
This could be a good start, but we need the yoast title and description of taxonomies and home as well:
https://wordpress.org/plugins/wp-api-yoast-meta/

**Comment by Poliuk** [comment]
```php
	/**
	 * Used for category, tag, and tax titles.
	 *
	 * @return string
	 */
	public function get_taxonomy_title() 
```

**Comment by Poliuk** [comment]
Done in this plugin: 

https://github.com/worona/wp-api-yoast-meta

**Comment by Poliuk** [comment]
Working on https://aztv.grupoadslzone.com/?rest_route=/wp/v2/posts
