### ISSUE TITLE
Insert field term-target & post-target in the tags

### ISSUE THREAD

**Issue by orballo** [worona/worona-wp-plugin#43]
We have to insert it in the ads-tags the fields **`term-target`** & **`post-target`**

- [x] **`term-target`** available in **`categories`** and **`tags`**
> https://aztv.grupoadslzone.com/?rest_route=/wp/v2/categories/50
> https://aztv.grupoadslzone.com/?rest_route=/wp/v2/tags/75

- [x]  Field **`post-target`** available in **`posts`**
> https://aztv.grupoadslzone.com/?rest_route=/wp/v2/posts/181842

**Comment by Poliuk** [comment]
- Field **`term-target`** available in **`categories`** and **`tags`**
- And field **`post-target`** available in **`posts`**

**Comment by DAreRodz** [comment]
Closed in https://github.com/worona/saturn-app-theme-worona/commit/b36f5da74853ca75202bcb894333baa8f48fd4ef.
