### ISSUE TITLE
Include iframe for GTM

### ISSUE THREAD

**Issue by Poliuk** [worona/worona-wp-plugin#9]
`plugin.worona.io/index.html` -> `/var/www/worona-cdn/plugin/index.html`

`plugin.worona.io/index.html?eventname=X&prop1=Y&prop2=Z`

`Index.html` contains:
JS + GTM + send 

**JS:** 
_Turns the query into an object_

`?eventname=X&prop1=Y&prop2=Z` 
into 
`{event = "" , props = { prop1 = X , prop2 = Y, prop3 = Z} }`

**GTM:**  
_Initialise GTM_

**Send:** 
_Send the object_

**Comment by luisherranz** [comment]
Remember that is worona.org so we can share the cookie.

**Comment by Poliuk** [comment]
https://plugin.worona.org/index.html working. 

First parameter in the query_string has to be `event`

**Comment by Poliuk** [comment]
### events

`plugin-active`
`rest-api-installed`
`rest-api-active`
`rest-api-not-compatible`
`change-site-id`
`plugin-configured`
`plugin-support-subscribe`
`plugin-support-unsubscribe`

### props

`email`
`wp-url`
`site-name`
`wp-version`
`wp-lan` (language)
`worona-version`
`user-name`
`worona-siteid`
`worona-siteid-new` *only available in `change-site-id` event*
